#!/usr/bin/env php
<?php

use EKvedaras\CathodeRayTube\CommunicationsDevice;
use EKvedaras\CathodeRayTube\CPU\CPU;
use EKvedaras\CathodeRayTube\CPU\Throttle;
use EKvedaras\CathodeRayTube\CRT\ConsoleScreen;
use EKvedaras\CathodeRayTube\CRT\CRT;
use EKvedaras\CathodeRayTube\CRT\Dimensions;
use EKvedaras\CathodeRayTube\Program\Drawing\DrawBasedOnSpritePosition;
use EKvedaras\CathodeRayTube\Program\Drawing\SpritePosition\Sprite;
use EKvedaras\CathodeRayTube\Program\Drawing\SpritePosition\SpritePosition;
use EKvedaras\CathodeRayTube\Program\InstructionSet;
use Symfony\Component\Console\Output\ConsoleOutput;

require_once 'vendor/autoload.php';

$output = new ConsoleOutput();
$cpu = new CPU();

$throttle = new Throttle(microseconds: 10_000);
$throttle->attach(to: $cpu);

$crt = new CRT(
    screenPlate: new ConsoleScreen(
        dimensions: new Dimensions(40, 6),
        output: $output,
    ),
);
$device = new CommunicationsDevice(
    cpu: $cpu,
    display: $crt,
);

$program = new DrawBasedOnSpritePosition(
    spritePositionProgram: new SpritePosition(
        sprite: new Sprite('###'),
        instructionSet: InstructionSet::load(
            <<<'Assembly'
            addx 15
            addx -11
            addx 6
            addx -3
            addx 5
            addx -1
            addx -8
            addx 13
            addx 4
            noop
            addx -1
            addx 5
            addx -1
            addx 5
            addx -1
            addx 5
            addx -1
            addx 5
            addx -1
            addx -35
            addx 1
            addx 24
            addx -19
            addx 1
            addx 16
            addx -11
            noop
            noop
            addx 21
            addx -15
            noop
            noop
            addx -3
            addx 9
            addx 1
            addx -3
            addx 8
            addx 1
            addx 5
            noop
            noop
            noop
            noop
            noop
            addx -36
            noop
            addx 1
            addx 7
            noop
            noop
            noop
            addx 2
            addx 6
            noop
            noop
            noop
            noop
            noop
            addx 1
            noop
            noop
            addx 7
            addx 1
            noop
            addx -13
            addx 13
            addx 7
            noop
            addx 1
            addx -33
            noop
            noop
            noop
            addx 2
            noop
            noop
            noop
            addx 8
            noop
            addx -1
            addx 2
            addx 1
            noop
            addx 17
            addx -9
            addx 1
            addx 1
            addx -3
            addx 11
            noop
            noop
            addx 1
            noop
            addx 1
            noop
            noop
            addx -13
            addx -19
            addx 1
            addx 3
            addx 26
            addx -30
            addx 12
            addx -1
            addx 3
            addx 1
            noop
            noop
            noop
            addx -9
            addx 18
            addx 1
            addx 2
            noop
            noop
            addx 9
            noop
            noop
            noop
            addx -1
            addx 2
            addx -37
            addx 1
            addx 3
            noop
            addx 15
            addx -21
            addx 22
            addx -6
            addx 1
            noop
            addx 2
            addx 1
            noop
            addx -10
            noop
            noop
            addx 20
            addx 1
            addx 2
            addx 2
            addx -6
            addx -11
            noop
            noop
            noop
            Assembly
        ),
    ),
    crt: $crt,
);

$device->run($program);

$output->write("\n");