#!/usr/bin/env php
<?php

use EKvedaras\CathodeRayTube\CommunicationsDevice;
use EKvedaras\CathodeRayTube\CPU\CPU;
use EKvedaras\CathodeRayTube\CPU\Throttle;
use EKvedaras\CathodeRayTube\CRT\ConsoleScreen;
use EKvedaras\CathodeRayTube\CRT\CRT;
use EKvedaras\CathodeRayTube\CRT\Dimensions;
use EKvedaras\CathodeRayTube\Program\Drawing\DrawBasedOnSpritePosition;
use EKvedaras\CathodeRayTube\Program\Drawing\SpritePosition\Sprite;
use EKvedaras\CathodeRayTube\Program\Drawing\SpritePosition\SpritePosition;
use EKvedaras\CathodeRayTube\Program\InstructionSet;
use Symfony\Component\Console\Output\ConsoleOutput;

require_once 'vendor/autoload.php';

$input = explode("\n", (string) file_get_contents($argv[1]));
[$width, $height] = explode('x', array_shift($input));
$sourceCode = implode("\n", $input);

$output = new ConsoleOutput();
$cpu = new CPU();

$throttle = new Throttle(microseconds: (int) ($argv[2] ?? 5_000));
$throttle->attach(to: $cpu);

$crt = new CRT(
    screenPlate: new ConsoleScreen(
        dimensions: new Dimensions((int) $width, (int) $height),
        output: $output,
    ),
);
$device = new CommunicationsDevice(
    cpu: $cpu,
    display: $crt,
);

$program = new DrawBasedOnSpritePosition(
    spritePositionProgram: new SpritePosition(
        sprite: new Sprite('###'),
        instructionSet: InstructionSet::load($sourceCode),
    ),
    crt: $crt,
);

$device->run($program);

$output->write("\n");